### ISSUE TITLE
TypeError: Object #<Server> has no method 'get'

### ISSUE THREAD

**Issue by NHQ** [ql-io/cluster2#21]
I get this error, and tho it does not stop cluster2 from working, it is quite annoying and fills my logs.

TypeError: Object #<Server> has no method 'get'
    at Object.exports.enable (/Users/jonsimpson/development/netmorphic/node_modules/cluster2/lib/ecv.js:35:9)
    at Server.Process.listen.conn.setTimeout.self.emitter.emit.message (/Users/jonsimpson/development/netmorphic/node_modules/cluster2/lib/process.js:289:27)
    at Server.g (events.js:193:14)
    at Server.EventEmitter.emit (events.js:123:20)
    at Server._listen2 (net.js:922:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

**Comment by shimonchayim** [comment]
issue now resolved. ECV functionality will not be available for tcp server.
