### ISSUE TITLE
HTTP Server Startup Error

### ISSUE THREAD

**Issue by jadent** [ql-io/cluster2#3]
When trying the "Start a HTTP Server" example w/o any modifications i receive an error for each worker. I'm using 
- Node v0.6.19 
- latest release of cluster2
- Ubuntu 11.10

The express example works w/o issue.

Master 13069 started
TypeError: Object #<Server> has no method 'get'
    at Object.enable (/var/www/node_modules/cluster2/lib/ecv.js:35:9)
    at /var/www/node_modules/cluster2/lib/index.js:83:29
    at HTTPServer.<anonymous> (/var/www/node_modules/cluster2/lib/process.js:220:16)
    at HTTPServer.emit (events.js:88:20)
    at Array.0 (net.js:777:10)
    at EventEmitter._tickCallback (node.js:190:38)
Running
Worker 13073 listening on 3000
TypeError: Object #<Server> has no method 'get'
    at Object.enable (/var/www/node_modules/cluster2/lib/ecv.js:35:9)
    at Server.<anonymous> (/var/www/node_modules/cluster2/lib/process.js:272:27)
    at Server.g (events.js:156:14)
    at Server.emit (events.js:88:20)
    at Array.0 (net.js:777:10)
    at EventEmitter._tickCallback (node.js:190:38)

**Comment by shimonchayim** [comment]
This was happening when starting TCP server, where ecv check was being registered assuming that the server is HTTP. Issue is resolved now.
