### ISSUE TITLE
TypeError, undefined property in non-clustered mode using express

### ISSUE THREAD

**Issue by simonrw** [ql-io/cluster2#30]
The express example in the documentation throws an exception with the cluster option `cluster: false`
### Server code

``` javascript
var Cluster = require('cluster2');
var express = require('express');

var app = express();
app.get('/', function(req, res) {
    res.send('hello');
});

var c = new Cluster({
    port: 3000,
    cluster: false
});

c.listen(function(cb) {
    cb(app);
});
```
### Error

```
TypeError: Cannot read property 'app' of undefined
    at exports.enable (/private/tmp/node_modules/cluster2/lib/ecv.js:37:30)
    at Function._.each._.forEach (/private/tmp/node_modules/cluster2/node_modules/underscore/underscore.js:81:22)
    at Object.exports.enable (/private/tmp/node_modules/cluster2/lib/ecv.js:36:7)
    at Server.Cluster.listen.createApp.call.ports (/private/tmp/node_modules/cluster2/lib/index.js:107:25)
    at Server.g (events.js:192:14)
    at Server.EventEmitter.emit (events.js:93:17)
    at Server._listen2 (net.js:923:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```
### Versions
- node v0.8.16
- express v3.0.6
- cluster2 v0.3.8

**Comment by shimonchayim** [comment]
Got it fixing it ...
