### ISSUE TITLE
TypeError: Cannot read property 'port' of null on cluster.js 

### ISSUE THREAD

**Issue by lagoasoft-lucasschmidt** [ql-io/cluster2#42]
Hey, I just started trying this out, and I had an error, described below. The thing is that I thought it had something to do with my code. But then I tried a simple application like the one below and still have this problem. The application works, but I just thought about posting here to see if anyone has any idea about this. Thank you!

var Cluster = require('cluster2');
var express = require('express');

var app = express();
app.get('/', function(req, res) {
    res.send('hello');
});

var c = new Cluster({
    port: 3000,
    cluster: false
});

c.listen(function(cb) {
    cb(app);
});

TypeError: Cannot read property 'port' of null
    at Server.<anonymous> (cluster.js:569:30)
    at Server.g (events.js:175:14)
    at Server.EventEmitter.emit (events.js:117:20)
    at net.js:1029:10
    at process._tickCallback (node.js:415:13)

express@3.1.0
node@0.10.5
cluster2@0.3.9

**Comment by jnaveeth** [comment]
I've also been seeing the same error on my console, although the application works properly.

**Comment by inexplicable** [comment]
in fact, this is an issue caused by node's cluster module 
https://github.com/joyent/node/blob/v0.8.23-release/lib/cluster.js
https://github.com/joyent/node/blob/v0.10.7-release/lib/cluster.js

compare the following:
// Send a listening message to the master
tcpSelf.once('listening', function() {
    cluster.worker.state = 'listening';
    sendInternalMessage(cluster.worker, {
      cmd: 'listening',
      address: address,
      port: port,
      addressType: addressType,
      fd: fd
    });
  });

//0.10.7
  tcpSelf.once('listening', function() {
    cluster.worker.state = 'listening';
    sendInternalMessage(cluster.worker, {
      cmd: 'listening',
      address: address,
      port: tcpSelf.address().port || port,
      addressType: addressType,
      fd: fd
    });
  });

the reading of tcpSelf.address().port is causing the error, as the net.js uses process.nextTick to emit 'listening' event and address isn't made available yet.

in most cases, i don't see it blocking the application though, let us know if otherwise

**Comment by ijse** [comment]
So, the solution is....

**Comment by lagoasoft-lucasschmidt** [comment]
Well, @ijse, since I found another problem in cluster2 module, I decided to not use it. I am using cluster module from node.

**Comment by ijse** [comment]
@lucastschmidt Thanks for your advice.   What's the problem? I just found it suit my case except the bug. Do you have any other alternatives?

**Comment by inexplicable** [comment]
i could try overwrite the Socket.prototype.address at best in net.js to return none null value to avoid the error message, but doesn't look safe at all. Also, looking at 0.11.x, they have eliminated such need: https://github.com/joyent/node/blob/v0.11.7-release/lib/cluster.js

obj.once('listening', function() {
      cluster.worker.state = 'listening';
      var address = obj.address();
      message.act = 'listening';
      message.port = address && address.port || port,
      send(message);
    });

**Comment by lagoasoft-lucasschmidt** [comment]
@ijse I am not using cluster2 because of this bug https://github.com/ql-io/cluster2/issues/43 

It was completely insane. Eventually I just used the vanilla http://nodejs.org/api/cluster.html

I didnt need anything special, so it was no problem for me.

 Another thing you could take a look into it is https://github.com/Unitech/pm2

I dont know if this project is active, but good luck!

**Comment by ijse** [comment]
@inexplicable 
@lucastschmidt  Thank you! I'll try pm2.

**Comment by adamziel** [comment]
In case anyone stumbles upon this issue, this monkey-patch at the beggining of worker file helps:

```
  cluster = require('cluster');


  $getServer = cluster._getServer;

  cluster._getServer = function(tcpSelf, address, port, addressType, fd, cb) {
    var $address;
    $address = tcpSelf.address;
    tcpSelf.address = function() {
      address = $address.apply(tcpSelf, arguments);
      if (!address) {
        address = {
          port: port
        };
      }
      return address;
    };
    return $getServer.apply($getServer, arguments);
  };
```

**Comment by aripalo** [comment]
Well this was annoying bug (in NodeJS cluster module that is, not this project)... couple hours wasted as I thought my code had a bug.
