### ISSUE TITLE
Receive Object is not a function creating a cluster

### ISSUE THREAD

**Issue by ztolley** [ql-io/cluster2#47]
I'm trying to setup a cluster for an express app but keep getting an error.

I've even tried using the example code on the github page but when I run it I get:

/Users/ztolley/example/test.js:8
var c = new Cluster({
        ^
TypeError: object is not a function
    at Object.<anonymous> (/Users/ztolley/example/test.js:8:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

**Comment by ElliotChong** [comment]
:+1: Ditto

**Comment by notsoluckycharm** [comment]
+1
