### ISSUE TITLE
/deps broken due to npm changes

### ISSUE THREAD

**Issue by s3u** [ql-io/cluster2#6]
cd cluster2
node examples/express/express-server.js 

Master 85997 started
Worker 85998 forked
Worker 85999 forked
Worker 86000 forked
Worker 86001 forked
Worker 85999 listening on 3000
Worker 86000 listening on 3000
Worker 85998 listening on 3000
Worker 86001 listening on 3000
TypeError: Object #<Object> has no method 'map'
    at EventEmitter.ls (/Users/subrah/dev/cluster2/node_modules/npm/lib/ls.js:29:20)
    at Object.<anonymous> (/Users/subrah/dev/cluster2/node_modules/npm/lib/npm.js:182:11)
    at EventEmitter.<anonymous> (/Users/subrah/dev/cluster2/lib/monitor.js:85:26)
    at Array.0 (native)
    at EventEmitter._tickCallback (node.js:190:38)

**Comment by shimonchayim** [comment]
Issue now resolved http://localhost:3001/deps works as expected
